# Generated by Django 5.2.9 on 2026-02-24 20:42

import django.db.models.deletion
import raida.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('language', models.CharField(choices=[('fr', 'French'), ('ar', 'Arabic')], max_length=10)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Teacher Info',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('français', 'Français'), ('mathématiques', 'Mathématiques'), ('langue arabe', 'Langue Arabe')], default='français', max_length=50)),
                ('level', models.CharField(blank=True, default='', max_length=10)),
                ('period', models.CharField(blank=True, default='', max_length=10)),
                ('week', models.CharField(blank=True, default='', max_length=10)),
                ('session', models.CharField(blank=True, default='', max_length=10)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('objective', models.TextField(blank=True, default='......')),
                ('content', models.TextField(blank=True, default='')),
                ('processed_content', models.JSONField(blank=True, null=True)),
                ('pptx_file', models.FileField(blank=True, null=True, upload_to='lessons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=raida.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/')),
                ('filename', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(default=raida.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='raida.lesson')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
