# Generated by Django 5.2.9 on 2026-02-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='language',
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='annee_scolaire',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='etablissement',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='etablissement_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='niveau',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='niveau_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='nom_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='ppr',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
