# Generated by Django 5.2.9 on 2026-03-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raida', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='show_ministry_logo',
            field=models.BooleanField(default=True),
        ),
    ]
