# Generated by Django 5.2.9 on 2026-03-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raida', '0005_lesson_last_generated_at_lesson_pdf_generation_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='color_preset',
            field=models.CharField(choices=[('professional', 'Professional (Blue)'), ('vibrant', 'Vibrant (Purple)'), ('calm', 'Calm (Green)')], default='professional', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small (10px)'), ('medium', 'Medium (12px)'), ('large', 'Large (14px)')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='line_height',
            field=models.CharField(choices=[('compact', 'Compact (1.3)'), ('comfortable', 'Comfortable (1.6)')], default='comfortable', max_length=15),
        ),
    ]
